# Site settings
baseurl = "http://izqui.github.io" #without ending slash
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Jorge Izquierdo"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-76689321-1"

[params]

	# Images settings
	# Icons, backgrounds and avatars folders are placed in theme's static/images folder.
	# You may place your images in corresponding folders and then set only filenames below to
	# change page's appearance

	favicon = "favicon.ico"
	appletouchicon = "apple-touch-icon-precomposed.png"
	background = "1.jpeg"
	avatar = "jorge.jpeg"

	# Personal settings

  name = "Jorge Izquierdo"
	position = "Mobile developer"

	# Extra stuff
	# NOTE: There is little different extra stuff in original Identity theme by HTML5 UP.
	# You can play with it downlading original theme right here:
	# html5up.net/identity/download
	#
	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
	# - enable form by setting 'enable' to 'true'
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

	email = "your@email.com"

	# Contact form settings

	[params.contact]
		enable = false
		formTitle = "Touch Me!"
		namePlaceholder = "Name"
		emailPlaceholder = "Email"
		messagePlaceholder = "Message"
		buttonText = "Send it"

	# Social settings
	# You may change these with your social links or add others


	[[params.social]]
		title = "Github"
		icon = "fa-github"
		link = "https://github.com/izqui"

	[[params.social]]
	  title = "Telegram"
	  icon = "fa-paper-plane"
	  link = "https://telegram.me/izqui"

	[[params.social]]
		title = "Twitter"
		icon = "fa-twitter"
		link = "https://twitter.com/izqui9"

	[[params.social]]
		title = "Instagram"
		icon = "fa-instagram"
		link = "https://instagram.com/izqui9"

	[[params.social]]
		title = "Linked In"
		icon = "fa-linkedin"
		link = "https://linkedin.com/izqui"

	# Footer settings
	[params.footer]
		copyright = "2016"
		title = "Source"
		url = "http://github.com/izqui/izqui.me"
